name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binaries
        run: make dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            urd_linux_amd64.zip
            urd_osx_amd64.zip
            urd_osx_arm64.zip
            urd_windows_amd64.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}